version: '2'
services:

  game-api:
    build:
      context: jvm/
    volumes:
      - ../project:/app
    environment:
      - JAR_NAME=app/target/game.jar
    ports:
      - 8085:80

  maven:
    build:
      context: maven/
    volumes:
      - ../project:/app
