version: '2'
services:

  mysql:
    image: mysql:8.0.2
    volumes:
      - ./.volumes/mysql:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d # database init files here.
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes" # easier to use for development cluster
    ports:
      - "3306:3306"

  game-api:
    build:
      context: jvm/
    volumes:
      - ../project:/app
    environment:
      - JAR_NAME=app/target/game.jar

  maven:
    build:
      context: maven/
    volumes:
      - ../project:/app
